### ISSUE TITLE
snake program is become lengthy , make it short to save data

### ISSUE THREAD

**Issue by Ash-00000** [Ash-00000/GAME#2]
Within the Snake class, how does the update method handle the snake's movement and collision detection, and how does it ensure the snake remains within the game grid?

**Comment by KIRAN-KUMAR-K3** [comment]
The `update` method in the `Snake` class calculates the new head position based on the current direction, ensures the snake wraps around the game grid, and checks for collisions with itself. If a collision occurs, the `reset` method is called to reset the snake's state. If no collision occurs, the new head position is added to the snake's positions, and if the length exceeds the specified limit, the tail is truncated to maintain the desired length.

**Comment by Ash-00000** [comment]
thankyou can you custumize it

**Comment by KIRAN-KUMAR-K3** [comment]
okey shore
